// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/signet/v1/signet.proto

package signetv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SignetService_VerifyIntegrity_FullMethodName = "/signet.v1.SignetService/VerifyIntegrity"
	SignetService_Check_FullMethodName           = "/signet.v1.SignetService/Check"
	SignetService_Promote_FullMethodName         = "/signet.v1.SignetService/Promote"
	SignetService_GetSeal_FullMethodName         = "/signet.v1.SignetService/GetSeal"
)

// SignetServiceClient is the client API for SignetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignetServiceClient interface {
	// VerifyIntegrity checks the CI workflow file for tampering.
	VerifyIntegrity(ctx context.Context, in *VerifyIntegrityRequest, opts ...grpc.CallOption) (*VerifyIntegrityResponse, error)
	// Check runs a governance scan on a code diff.
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	// Promote initiates the movement of a sealed artifact to a target environment.
	Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error)
	// GetSeal retrieves a specific seal and its evidence from the ledger.
	GetSeal(ctx context.Context, in *GetSealRequest, opts ...grpc.CallOption) (*GetSealResponse, error)
}

type signetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignetServiceClient(cc grpc.ClientConnInterface) SignetServiceClient {
	return &signetServiceClient{cc}
}

func (c *signetServiceClient) VerifyIntegrity(ctx context.Context, in *VerifyIntegrityRequest, opts ...grpc.CallOption) (*VerifyIntegrityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyIntegrityResponse)
	err := c.cc.Invoke(ctx, SignetService_VerifyIntegrity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signetServiceClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, SignetService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signetServiceClient) Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromoteResponse)
	err := c.cc.Invoke(ctx, SignetService_Promote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signetServiceClient) GetSeal(ctx context.Context, in *GetSealRequest, opts ...grpc.CallOption) (*GetSealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSealResponse)
	err := c.cc.Invoke(ctx, SignetService_GetSeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignetServiceServer is the server API for SignetService service.
// All implementations must embed UnimplementedSignetServiceServer
// for forward compatibility.
type SignetServiceServer interface {
	// VerifyIntegrity checks the CI workflow file for tampering.
	VerifyIntegrity(context.Context, *VerifyIntegrityRequest) (*VerifyIntegrityResponse, error)
	// Check runs a governance scan on a code diff.
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	// Promote initiates the movement of a sealed artifact to a target environment.
	Promote(context.Context, *PromoteRequest) (*PromoteResponse, error)
	// GetSeal retrieves a specific seal and its evidence from the ledger.
	GetSeal(context.Context, *GetSealRequest) (*GetSealResponse, error)
	mustEmbedUnimplementedSignetServiceServer()
}

// UnimplementedSignetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignetServiceServer struct{}

func (UnimplementedSignetServiceServer) VerifyIntegrity(context.Context, *VerifyIntegrityRequest) (*VerifyIntegrityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyIntegrity not implemented")
}
func (UnimplementedSignetServiceServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedSignetServiceServer) Promote(context.Context, *PromoteRequest) (*PromoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Promote not implemented")
}
func (UnimplementedSignetServiceServer) GetSeal(context.Context, *GetSealRequest) (*GetSealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSeal not implemented")
}
func (UnimplementedSignetServiceServer) mustEmbedUnimplementedSignetServiceServer() {}
func (UnimplementedSignetServiceServer) testEmbeddedByValue()                       {}

// UnsafeSignetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignetServiceServer will
// result in compilation errors.
type UnsafeSignetServiceServer interface {
	mustEmbedUnimplementedSignetServiceServer()
}

func RegisterSignetServiceServer(s grpc.ServiceRegistrar, srv SignetServiceServer) {
	// If the following call pancis, it indicates UnimplementedSignetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SignetService_ServiceDesc, srv)
}

func _SignetService_VerifyIntegrity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyIntegrityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignetServiceServer).VerifyIntegrity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignetService_VerifyIntegrity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignetServiceServer).VerifyIntegrity(ctx, req.(*VerifyIntegrityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignetService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignetServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignetService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignetServiceServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignetService_Promote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignetServiceServer).Promote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignetService_Promote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignetServiceServer).Promote(ctx, req.(*PromoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignetService_GetSeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignetServiceServer).GetSeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignetService_GetSeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignetServiceServer).GetSeal(ctx, req.(*GetSealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SignetService_ServiceDesc is the grpc.ServiceDesc for SignetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "signet.v1.SignetService",
	HandlerType: (*SignetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyIntegrity",
			Handler:    _SignetService_VerifyIntegrity_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _SignetService_Check_Handler,
		},
		{
			MethodName: "Promote",
			Handler:    _SignetService_Promote_Handler,
		},
		{
			MethodName: "GetSeal",
			Handler:    _SignetService_GetSeal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/signet/v1/signet.proto",
}
