// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/signet/v1/signet.proto

package signetv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckResponse_Verdict int32

const (
	CheckResponse_VERDICT_UNSPECIFIED CheckResponse_Verdict = 0
	CheckResponse_VERDICT_PASS        CheckResponse_Verdict = 1
	CheckResponse_VERDICT_WARN        CheckResponse_Verdict = 2
	CheckResponse_VERDICT_FAIL        CheckResponse_Verdict = 3
)

// Enum value maps for CheckResponse_Verdict.
var (
	CheckResponse_Verdict_name = map[int32]string{
		0: "VERDICT_UNSPECIFIED",
		1: "VERDICT_PASS",
		2: "VERDICT_WARN",
		3: "VERDICT_FAIL",
	}
	CheckResponse_Verdict_value = map[string]int32{
		"VERDICT_UNSPECIFIED": 0,
		"VERDICT_PASS":        1,
		"VERDICT_WARN":        2,
		"VERDICT_FAIL":        3,
	}
)

func (x CheckResponse_Verdict) Enum() *CheckResponse_Verdict {
	p := new(CheckResponse_Verdict)
	*p = x
	return p
}

func (x CheckResponse_Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckResponse_Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_signet_v1_signet_proto_enumTypes[0].Descriptor()
}

func (CheckResponse_Verdict) Type() protoreflect.EnumType {
	return &file_proto_signet_v1_signet_proto_enumTypes[0]
}

func (x CheckResponse_Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckResponse_Verdict.Descriptor instead.
func (CheckResponse_Verdict) EnumDescriptor() ([]byte, []int) {
	return file_proto_signet_v1_signet_proto_rawDescGZIP(), []int{3, 0}
}

type VerifyIntegrityRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkflowPath    string                 `protobuf:"bytes,1,opt,name=workflow_path,json=workflowPath,proto3" json:"workflow_path,omitempty"`
	WorkflowContent string                 `protobuf:"bytes,2,opt,name=workflow_content,json=workflowContent,proto3" json:"workflow_content,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VerifyIntegrityRequest) Reset() {
	*x = VerifyIntegrityRequest{}
	mi := &file_proto_signet_v1_signet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyIntegrityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyIntegrityRequest) ProtoMessage() {}

func (x *VerifyIntegrityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signet_v1_signet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyIntegrityRequest.ProtoReflect.Descriptor instead.
func (*VerifyIntegrityRequest) Descriptor() ([]byte, []int) {
	return file_proto_signet_v1_signet_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyIntegrityRequest) GetWorkflowPath() string {
	if x != nil {
		return x.WorkflowPath
	}
	return ""
}

func (x *VerifyIntegrityRequest) GetWorkflowContent() string {
	if x != nil {
		return x.WorkflowContent
	}
	return ""
}

type VerifyIntegrityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyIntegrityResponse) Reset() {
	*x = VerifyIntegrityResponse{}
	mi := &file_proto_signet_v1_signet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyIntegrityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyIntegrityResponse) ProtoMessage() {}

func (x *VerifyIntegrityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signet_v1_signet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyIntegrityResponse.ProtoReflect.Descriptor instead.
func (*VerifyIntegrityResponse) Descriptor() ([]byte, []int) {
	return file_proto_signet_v1_signet_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyIntegrityResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyIntegrityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoUrl       string                 `protobuf:"bytes,1,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	CommitSha     string                 `protobuf:"bytes,3,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	Patch         []byte                 `protobuf:"bytes,4,opt,name=patch,proto3" json:"patch,omitempty"` // The code diff
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_proto_signet_v1_signet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signet_v1_signet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_signet_v1_signet_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *CheckRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *CheckRequest) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *CheckRequest) GetPatch() []byte {
	if x != nil {
		return x.Patch
	}
	return nil
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verdict       CheckResponse_Verdict  `protobuf:"varint,1,opt,name=verdict,proto3,enum=signet.v1.CheckResponse_Verdict" json:"verdict,omitempty"`
	SealId        string                 `protobuf:"bytes,2,opt,name=seal_id,json=sealId,proto3" json:"seal_id,omitempty"` // Only present if PASS or WARN (if allowed)
	Findings      []*Finding             `protobuf:"bytes,3,rep,name=findings,proto3" json:"findings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_proto_signet_v1_signet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signet_v1_signet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_signet_v1_signet_proto_rawDescGZIP(), []int{3}
}

func (x *CheckResponse) GetVerdict() CheckResponse_Verdict {
	if x != nil {
		return x.Verdict
	}
	return CheckResponse_VERDICT_UNSPECIFIED
}

func (x *CheckResponse) GetSealId() string {
	if x != nil {
		return x.SealId
	}
	return ""
}

func (x *CheckResponse) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

type Finding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	File          string                 `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	Line          int32                  `protobuf:"varint,4,opt,name=line,proto3" json:"line,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Remediation   string                 `protobuf:"bytes,6,opt,name=remediation,proto3" json:"remediation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_proto_signet_v1_signet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signet_v1_signet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_proto_signet_v1_signet_proto_rawDescGZIP(), []int{4}
}

func (x *Finding) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Finding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Finding) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Finding) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Finding) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Finding) GetRemediation() string {
	if x != nil {
		return x.Remediation
	}
	return ""
}

type PromoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SealId        string                 `protobuf:"bytes,1,opt,name=seal_id,json=sealId,proto3" json:"seal_id,omitempty"`
	TargetEnv     string                 `protobuf:"bytes,2,opt,name=target_env,json=targetEnv,proto3" json:"target_env,omitempty"`
	AutoMerge     bool                   `protobuf:"varint,3,opt,name=auto_merge,json=autoMerge,proto3" json:"auto_merge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteRequest) Reset() {
	*x = PromoteRequest{}
	mi := &file_proto_signet_v1_signet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteRequest) ProtoMessage() {}

func (x *PromoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signet_v1_signet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteRequest.ProtoReflect.Descriptor instead.
func (*PromoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_signet_v1_signet_proto_rawDescGZIP(), []int{5}
}

func (x *PromoteRequest) GetSealId() string {
	if x != nil {
		return x.SealId
	}
	return ""
}

func (x *PromoteRequest) GetTargetEnv() string {
	if x != nil {
		return x.TargetEnv
	}
	return ""
}

func (x *PromoteRequest) GetAutoMerge() bool {
	if x != nil {
		return x.AutoMerge
	}
	return false
}

type PromoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrUrl         string                 `protobuf:"bytes,1,opt,name=pr_url,json=prUrl,proto3" json:"pr_url,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteResponse) Reset() {
	*x = PromoteResponse{}
	mi := &file_proto_signet_v1_signet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteResponse) ProtoMessage() {}

func (x *PromoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signet_v1_signet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteResponse.ProtoReflect.Descriptor instead.
func (*PromoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_signet_v1_signet_proto_rawDescGZIP(), []int{6}
}

func (x *PromoteResponse) GetPrUrl() string {
	if x != nil {
		return x.PrUrl
	}
	return ""
}

func (x *PromoteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetSealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SealId        string                 `protobuf:"bytes,1,opt,name=seal_id,json=sealId,proto3" json:"seal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSealRequest) Reset() {
	*x = GetSealRequest{}
	mi := &file_proto_signet_v1_signet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSealRequest) ProtoMessage() {}

func (x *GetSealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signet_v1_signet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSealRequest.ProtoReflect.Descriptor instead.
func (*GetSealRequest) Descriptor() ([]byte, []int) {
	return file_proto_signet_v1_signet_proto_rawDescGZIP(), []int{7}
}

func (x *GetSealRequest) GetSealId() string {
	if x != nil {
		return x.SealId
	}
	return ""
}

type GetSealResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SealId          string                 `protobuf:"bytes,1,opt,name=seal_id,json=sealId,proto3" json:"seal_id,omitempty"`
	ArtifactSha     string                 `protobuf:"bytes,2,opt,name=artifact_sha,json=artifactSha,proto3" json:"artifact_sha,omitempty"`
	Verdict         string                 `protobuf:"bytes,3,opt,name=verdict,proto3" json:"verdict,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	EvidencePayload []byte                 `protobuf:"bytes,5,opt,name=evidence_payload,json=evidencePayload,proto3" json:"evidence_payload,omitempty"` // JSON/CUE evidence
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSealResponse) Reset() {
	*x = GetSealResponse{}
	mi := &file_proto_signet_v1_signet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSealResponse) ProtoMessage() {}

func (x *GetSealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signet_v1_signet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSealResponse.ProtoReflect.Descriptor instead.
func (*GetSealResponse) Descriptor() ([]byte, []int) {
	return file_proto_signet_v1_signet_proto_rawDescGZIP(), []int{8}
}

func (x *GetSealResponse) GetSealId() string {
	if x != nil {
		return x.SealId
	}
	return ""
}

func (x *GetSealResponse) GetArtifactSha() string {
	if x != nil {
		return x.ArtifactSha
	}
	return ""
}

func (x *GetSealResponse) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *GetSealResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetSealResponse) GetEvidencePayload() []byte {
	if x != nil {
		return x.EvidencePayload
	}
	return nil
}

var File_proto_signet_v1_signet_proto protoreflect.FileDescriptor

const file_proto_signet_v1_signet_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/signet/v1/signet.proto\x12\tsignet.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"h\n" +
	"\x16VerifyIntegrityRequest\x12#\n" +
	"\rworkflow_path\x18\x01 \x01(\tR\fworkflowPath\x12)\n" +
	"\x10workflow_content\x18\x02 \x01(\tR\x0fworkflowContent\"I\n" +
	"\x17VerifyIntegrityResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"v\n" +
	"\fCheckRequest\x12\x19\n" +
	"\brepo_url\x18\x01 \x01(\tR\arepoUrl\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x03 \x01(\tR\tcommitSha\x12\x14\n" +
	"\x05patch\x18\x04 \x01(\fR\x05patch\"\xee\x01\n" +
	"\rCheckResponse\x12:\n" +
	"\averdict\x18\x01 \x01(\x0e2 .signet.v1.CheckResponse.VerdictR\averdict\x12\x17\n" +
	"\aseal_id\x18\x02 \x01(\tR\x06sealId\x12.\n" +
	"\bfindings\x18\x03 \x03(\v2\x12.signet.v1.FindingR\bfindings\"X\n" +
	"\aVerdict\x12\x17\n" +
	"\x13VERDICT_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fVERDICT_PASS\x10\x01\x12\x10\n" +
	"\fVERDICT_WARN\x10\x02\x12\x10\n" +
	"\fVERDICT_FAIL\x10\x03\"\x9d\x01\n" +
	"\aFinding\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x12\n" +
	"\x04file\x18\x03 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x04 \x01(\x05R\x04line\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12 \n" +
	"\vremediation\x18\x06 \x01(\tR\vremediation\"g\n" +
	"\x0ePromoteRequest\x12\x17\n" +
	"\aseal_id\x18\x01 \x01(\tR\x06sealId\x12\x1d\n" +
	"\n" +
	"target_env\x18\x02 \x01(\tR\ttargetEnv\x12\x1d\n" +
	"\n" +
	"auto_merge\x18\x03 \x01(\bR\tautoMerge\"@\n" +
	"\x0fPromoteResponse\x12\x15\n" +
	"\x06pr_url\x18\x01 \x01(\tR\x05prUrl\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\")\n" +
	"\x0eGetSealRequest\x12\x17\n" +
	"\aseal_id\x18\x01 \x01(\tR\x06sealId\"\xcd\x01\n" +
	"\x0fGetSealResponse\x12\x17\n" +
	"\aseal_id\x18\x01 \x01(\tR\x06sealId\x12!\n" +
	"\fartifact_sha\x18\x02 \x01(\tR\vartifactSha\x12\x18\n" +
	"\averdict\x18\x03 \x01(\tR\averdict\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12)\n" +
	"\x10evidence_payload\x18\x05 \x01(\fR\x0fevidencePayload2\xa9\x02\n" +
	"\rSignetService\x12X\n" +
	"\x0fVerifyIntegrity\x12!.signet.v1.VerifyIntegrityRequest\x1a\".signet.v1.VerifyIntegrityResponse\x12:\n" +
	"\x05Check\x12\x17.signet.v1.CheckRequest\x1a\x18.signet.v1.CheckResponse\x12@\n" +
	"\aPromote\x12\x19.signet.v1.PromoteRequest\x1a\x1a.signet.v1.PromoteResponse\x12@\n" +
	"\aGetSeal\x12\x19.signet.v1.GetSealRequest\x1a\x1a.signet.v1.GetSealResponseB:Z8github.com/geoffmilleraz/signet/proto/signet/v1;signetv1b\x06proto3"

var (
	file_proto_signet_v1_signet_proto_rawDescOnce sync.Once
	file_proto_signet_v1_signet_proto_rawDescData []byte
)

func file_proto_signet_v1_signet_proto_rawDescGZIP() []byte {
	file_proto_signet_v1_signet_proto_rawDescOnce.Do(func() {
		file_proto_signet_v1_signet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_signet_v1_signet_proto_rawDesc), len(file_proto_signet_v1_signet_proto_rawDesc)))
	})
	return file_proto_signet_v1_signet_proto_rawDescData
}

var file_proto_signet_v1_signet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_signet_v1_signet_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_signet_v1_signet_proto_goTypes = []any{
	(CheckResponse_Verdict)(0),      // 0: signet.v1.CheckResponse.Verdict
	(*VerifyIntegrityRequest)(nil),  // 1: signet.v1.VerifyIntegrityRequest
	(*VerifyIntegrityResponse)(nil), // 2: signet.v1.VerifyIntegrityResponse
	(*CheckRequest)(nil),            // 3: signet.v1.CheckRequest
	(*CheckResponse)(nil),           // 4: signet.v1.CheckResponse
	(*Finding)(nil),                 // 5: signet.v1.Finding
	(*PromoteRequest)(nil),          // 6: signet.v1.PromoteRequest
	(*PromoteResponse)(nil),         // 7: signet.v1.PromoteResponse
	(*GetSealRequest)(nil),          // 8: signet.v1.GetSealRequest
	(*GetSealResponse)(nil),         // 9: signet.v1.GetSealResponse
	(*timestamppb.Timestamp)(nil),   // 10: google.protobuf.Timestamp
}
var file_proto_signet_v1_signet_proto_depIdxs = []int32{
	0,  // 0: signet.v1.CheckResponse.verdict:type_name -> signet.v1.CheckResponse.Verdict
	5,  // 1: signet.v1.CheckResponse.findings:type_name -> signet.v1.Finding
	10, // 2: signet.v1.GetSealResponse.created_at:type_name -> google.protobuf.Timestamp
	1,  // 3: signet.v1.SignetService.VerifyIntegrity:input_type -> signet.v1.VerifyIntegrityRequest
	3,  // 4: signet.v1.SignetService.Check:input_type -> signet.v1.CheckRequest
	6,  // 5: signet.v1.SignetService.Promote:input_type -> signet.v1.PromoteRequest
	8,  // 6: signet.v1.SignetService.GetSeal:input_type -> signet.v1.GetSealRequest
	2,  // 7: signet.v1.SignetService.VerifyIntegrity:output_type -> signet.v1.VerifyIntegrityResponse
	4,  // 8: signet.v1.SignetService.Check:output_type -> signet.v1.CheckResponse
	7,  // 9: signet.v1.SignetService.Promote:output_type -> signet.v1.PromoteResponse
	9,  // 10: signet.v1.SignetService.GetSeal:output_type -> signet.v1.GetSealResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_signet_v1_signet_proto_init() }
func file_proto_signet_v1_signet_proto_init() {
	if File_proto_signet_v1_signet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_signet_v1_signet_proto_rawDesc), len(file_proto_signet_v1_signet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_signet_v1_signet_proto_goTypes,
		DependencyIndexes: file_proto_signet_v1_signet_proto_depIdxs,
		EnumInfos:         file_proto_signet_v1_signet_proto_enumTypes,
		MessageInfos:      file_proto_signet_v1_signet_proto_msgTypes,
	}.Build()
	File_proto_signet_v1_signet_proto = out.File
	file_proto_signet_v1_signet_proto_goTypes = nil
	file_proto_signet_v1_signet_proto_depIdxs = nil
}
